#!/usr/bin/env python3
"""
JAMA-style publication figures from deduped guideline data.
Clean, minimal, grayscale-safe.

Figure 1: Specialty evidence distribution (stacked bars, 2 panels)
Figure 2: % Level A vs % Level D-E by specialty (paired bars)
Figure 3: Evidence gap lollipop chart
eFigure 1: PRISMA flow diagram (generated by scripts/make_prisma.py, not here)
eFigure 2: Sensitivity ranking stability (efigure1() -> efigure2_sensitivity_ranking)
(Retired from the supplement: access coverage -> eTable 2;
 society-level distribution -> raw data in Supplementary Data File.)
"""

import json, statistics
from pathlib import Path
from collections import Counter, OrderedDict, defaultdict

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

DATA_DIR = Path(__file__).parent.parent / "data"
FIG_DIR = DATA_DIR / "figures"
FIG_DIR.mkdir(exist_ok=True)

# 5-tier palette — accessible, print-safe
C = OrderedDict([
    ('A', '#1b4f72'), ('B', '#2980b9'), ('C', '#85c1e9'),
    ('D', '#eb984e'), ('E', '#c0392b'),
])
C_LABELS = OrderedDict([
    ('A', 'A  Multiple RCTs'), ('B', 'B  Single RCT / moderate'),
    ('C', 'C  Observational / low'), ('D', 'D  Case series / very low'),
    ('E', 'E  Expert opinion'),
])

SHORT_SPECS = {
    'Obstetrics & Gynaecology': 'Obstetrics & Gynae.',
    'Allergy & Immunology': 'Allergy & Immuno.',
    'Orthopaedic Surgery': 'Orthopaedic Surg.',
    'Reproductive Medicine': 'Reproductive Med.',
    'Infectious Disease': 'Infectious Dis.',
    'Critical Care Medicine': 'Critical Care',
    'Geriatric Medicine': 'Geriatric Med.',
    'Vascular Surgery': 'Vascular Surg.',
    'Internal Medicine': 'Internal Med.',
    'General Surgery': 'General Surg.',
    'Trauma Surgery': 'Trauma Surg.',
    'Family Medicine': 'Family Med.',
}

NORM = {
    'A': 1.0, 'B-R': 0.75, 'B-NR': 0.5, 'C-LD': 0.25, 'C-EO': 0.125,
    'High': 1.0, 'Moderate': 0.75, 'Low': 0.5, 'Very Low': 0.25, 'Very low': 0.25,
    'I': 1.0, 'II': 0.75, 'III': 0.5, 'IV': 0.25, 'V': 0.125,
    'Expert consensus': 0.125, 'E': 0.125,
    '1a': 1.0, '1b': 1.0, '1': 1.0, '2a': 0.75, '2b': 0.75, '2': 0.75,
    '3': 0.5, '3a': 0.5, '3b': 0.5, '4': 0.25, '5': 0.125,
    'Level 1': 1.0, 'Level 2': 0.75, 'Level 3': 0.5, 'Level 4': 0.25,
    'B': 0.75, 'C': 0.5, 'U': 0.125, 'GPP': 0.125, 'D': 0.25,
    'Best Evidence': 1.0, 'Option': 0.125, 'Consensus': 0.125,
}
ESC_NORM = {'A': 1.0, 'B': 0.5, 'C': 0.25}
SKIP_STRENGTH = {'Strong', 'Weak', 'Strong Recommendation', 'Conditional', 'Conditional Recommendation'}
LOE_EXCLUDED = {'EAU', 'AAOS'}

# Denominators for eFigure 2
AUDIT_DENOM = {
    'AAAAI':8,'AACE':8,'AAD':8,'AAFP':5,'AAN':20,'AAO-HNS':25,'AAOS':25,'AAP':20,
    'AASLD':24,'ACG':49,'ACOG':50,'ACP':24,'ACS':5,'AGA':14,'AGS':5,'AHA':45,
    'APA':10,'ASCO':87,'ATS':20,'BSR':10,'BTS':10,'CANMAT':5,'EAACI':8,'EAN':10,
    'EAST':8,'ESHRE':31,'ESMO':35,'ESPEN':12,'EULAR':29,'IDSA':48,'ISTH':5,
    'KDIGO':18,'RCOG':29,'SAGES':5,'SCCM':40,'SHEA':8,'SVS':8,'WAO':5,'WFSBP':6,
}
FULLY_COMPLETE = {'ACR','ADA','ASH','BSG','EASL','EAU','ENDOCRINE','ERS','ESCMID','ESGE','GINA','GOLD'}


def _setup():
    matplotlib.rc('font', family='Arial', size=8)
    matplotlib.rc('axes', linewidth=0.5)
    for ax in ('xtick', 'ytick'):
        matplotlib.rc(ax, direction='out')
        matplotlib.rc(f'{ax}.major', width=0.5, size=3)

_setup()


def _tier(n):
    if n >= 1.0: return 'A'
    if n >= 0.75: return 'B'
    if n >= 0.5: return 'C'
    if n >= 0.25: return 'D'
    return 'E'


def _pct_sum100(counts, total):
    """One-decimal percentages that sum to exactly 100.0 (largest-remainder)."""
    tenths = [c / total * 1000 for c in counts]
    floor = [int(x) for x in tenths]
    need = round(sum(tenths)) - sum(floor)
    for i in sorted(range(len(tenths)), key=lambda k: tenths[k] - floor[k], reverse=True)[:need]:
        floor[i] += 1
    return [f / 10 for f in floor]


def _textc(bg):
    return '#fff' if bg in ('#1b4f72', '#2980b9', '#c0392b') else '#333'


def normalize_loe(loe, qual, society):
    if society in LOE_EXCLUDED:
        return None
    for val in [loe, qual]:
        if not val or str(val) in ('Not stated', 'None', '', 'nan', 'N/A'):
            continue
        val = str(val).strip()
        if val in SKIP_STRENGTH:
            continue
        if society == 'ESC' and val in ESC_NORM:
            return ESC_NORM[val]
        if val in NORM:
            return NORM[val]
    return None


def load_data():
    """Load from evidence_atlas.json (single source of truth, matches manuscript)."""
    atlas_path = DATA_DIR / "evidence_atlas.json"
    with open(atlas_path) as f:
        atlas = json.load(f)

    gl_map = {g['id']: g for g in atlas['guidelines']}

    recs_by_spec = defaultdict(list)
    recs_by_soc = defaultdict(list)
    soc_gl_count = Counter()
    spec_gl_count = Counter()
    soc_grading = defaultdict(Counter)

    for g in atlas['guidelines']:
        soc_gl_count[g['society']] += 1
        spec_gl_count[g['specialty']] += 1
        soc_grading[g['society']][g.get('grading_system', '?')] += 1

    for r in atlas['recommendations']:
        score = r.get('loe_normalized')
        if score is None:
            continue
        g = gl_map.get(r['guideline_id'], {})
        loe_label = r.get('loe', '')
        rec = {'score': score, 'tier': _tier(score), 'loe': loe_label,
               'society': r.get('society', g.get('society', '?')),
               'specialty': r.get('specialty', g.get('specialty', '?')),
               'guideline_id': r['guideline_id'],
               'grading': g.get('grading_system', '?'),
               'in_primary': bool(g.get('in_primary_analysis'))}
        recs_by_spec[rec['specialty']].append(rec)
        recs_by_soc[rec['society']].append(rec)

    return recs_by_spec, recs_by_soc, soc_gl_count, spec_gl_count, soc_grading


def primary_filter(recs_by_spec, spec_gl_count):
    """Filter to specialties with >=5 guidelines, using the canonical
    in_primary_analysis set (LoE-only societies, >=3 normalizable recs per
    guideline) so figure sample sizes match Table 1 / analysis.py."""
    return {s: [r for r in v if r.get('in_primary')]
            for s, v in recs_by_spec.items()
            if spec_gl_count.get(s, 0) >= 5
            and any(r.get('in_primary') for r in v)}


# ─────────────────────────────────────────────────
# Figure 1 — Specialty evidence distribution
# ─────────────────────────────────────────────────
def figure1(specs):
    specs = dict(specs)  # copy
    order = sorted(specs, key=lambda s: statistics.mean([r['score'] for r in specs[s]]))

    # Pooled distribution across all primary specialties -> "Overall" summary row
    all_recs = [r for sp in order for r in specs[sp]]
    # Rows top-to-bottom: Overall, then specialties (largest evidence gap first)
    rows = [('Overall', all_recs)] + [(SHORT_SPECS.get(s, s), specs[s]) for s in order]

    n_rows = len(rows)
    # JAMA: trimmed content lands at ~7 in wide (full width) and ~9 in tall
    # (≈ a portrait page) at 300 dpi; canvas is larger because bbox_inches
    # trims ~30% of the width.
    fig_h = max(5, 0.34 * n_rows + 1.3)
    fig, ax1 = plt.subplots(figsize=(10.5, fig_h))
    bh = 0.66

    # x positions for the exact-value columns to the right of the bars
    COL_X = {'A': 108, 'B': 118, 'C': 128, 'D': 138, 'E': 148}
    GAP_X = 160

    for yi, (label, recs) in enumerate(rows):
        total = len(recs)
        tc = Counter(r['tier'] for r in recs)
        # largest-remainder rounding so the printed %s and bar widths sum to 100.0
        pcts = _pct_sum100([tc.get(t, 0) for t in C], total)
        left = 0
        for t, pct in zip(C, pcts):
            if pct > 0:
                ax1.barh(yi, pct, left=left, height=bh, color=C[t], edgecolor='white', lw=0.3)
                left += pct
            # exact value for every tier, in an aligned column (readable even for <1% tiers)
            ax1.text(COL_X[t], yi, f'{pct:.1f}', ha='center', va='center', fontsize=8.5, color='#333')
        gap = 1 - statistics.mean([r['score'] for r in recs])
        ax1.text(GAP_X, yi, f'{gap:.2f}', ha='center', va='center', fontsize=9, fontweight='bold', color='#333')

    def _row_label(label, recs):
        n_soc = len({r['society'] for r in recs})
        n_gl = len({r['guideline_id'] for r in recs})
        return f'{label}  ({n_soc} soc, {n_gl} GL, n={len(recs):,})'

    ax1.set_yticks(range(n_rows))
    ax1.set_yticklabels([_row_label(label, recs) for label, recs in rows], fontsize=8.5)
    # Emphasize the Overall summary row
    ax1.get_yticklabels()[0].set_fontweight('bold')
    ax1.set_xlim(0, 100)
    ax1.invert_yaxis()
    # Trim the empty band above the header row and below the last bar
    ax1.set_ylim(n_rows - 0.5, -0.95)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    ax1.set_xlabel('% of Recommendations', fontsize=8.5)
    # Column headers for the exact-value table (% at each tier, then gap)
    for t, x in COL_X.items():
        ax1.text(x, -0.62, f'%{t}', ha='center', fontsize=9, fontweight='bold', color='#666')
    ax1.text(GAP_X, -0.62, 'Gap', ha='center', fontsize=9, fontweight='bold', color='#666')
    patches = [mpatches.Patch(color=c, label=C_LABELS[t]) for t, c in C.items()]
    ax1.legend(handles=patches, loc='upper center', bbox_to_anchor=(0.5, -0.075),
               fontsize=7.5, frameon=False, ncol=3, columnspacing=1.2, handlelength=1.2)

    fig.tight_layout()
    for fmt in ('pdf', 'png'):
        fig.savefig(FIG_DIR / f'figure2_evidence_distribution.{fmt}', dpi=300, bbox_inches='tight', pad_inches=0.03)
    plt.close(fig)
    print('Figure 1 saved')


# ─────────────────────────────────────────────────
# Figure 2 — Two-panel dot plot
# Panel A: n recs vs % Level A (all primary specialties)
# Panel B: n recs vs % Level D-E
# All labels hand-placed
# ─────────────────────────────────────────────────
def figure2(specs):
    specs = dict(specs)

    data = {}
    for sp, recs in specs.items():
        n = len(recs)
        pa = sum(1 for r in recs if r['tier'] == 'A') / n * 100
        pde = sum(1 for r in recs if r['tier'] in ('D', 'E')) / n * 100
        data[sp] = {'n': n, 'pct_a': pa, 'pct_de': pde}

    DOT_COLOR = '#2471a3'

    # Manual label offsets: (dx, dy) in points from dot center, ha
    # Positive dx = right, negative = left
    PANEL_A = {  # all 21 primary specialties; offsets tuned to avoid label overlap
        'Psychiatry':               (-10, 0, 'right'),
        'Orthopaedic Surgery':      (-8, 7, 'right'),
        'General Surgery':          (10, -7, 'left'),
        'Allergy & Immunology':     (8, 0, 'left'),
        'Otolaryngology':           (8, 0, 'left'),
        'Dermatology':              (-8, 7, 'right'),
        'Pulmonology':              (8, 5, 'left'),
        'Hepatology':               (8, -7, 'left'),
        'Oncology':                 (-8, 8, 'right'),
        'Nephrology':               (-8, 5, 'right'),
        'Cardiology':               (-8, 0, 'right'),
        'Endocrinology':            (8, -7, 'left'),
        'Pediatrics':               (-8, -5, 'right'),
        'Neurology':                (-8, 3, 'right'),
        'Infectious Disease':       (8, 6, 'left'),
        'Rheumatology':             (8, -7, 'left'),
        'Gastroenterology':         (8, 0, 'left'),
        'Critical Care Medicine':   (-8, 3, 'right'),
        'Obstetrics & Gynaecology': (8, 3, 'left'),
        'Hematology':               (8, -5, 'left'),
        'Reproductive Medicine':    (8, 0, 'left'),
    }

    PANEL_B = {  # all 21 primary specialties; offsets tuned to avoid label overlap
        'Obstetrics & Gynaecology': (8, 0, 'left'),
        'Reproductive Medicine':    (8, 0, 'left'),
        'Pulmonology':              (8, 0, 'left'),
        'Hematology':               (-8, 0, 'right'),
        'Allergy & Immunology':     (8, 0, 'left'),
        'Cardiology':               (8, 0, 'left'),
        'Endocrinology':            (8, 8, 'left'),
        'Oncology':                 (8, -9, 'left'),
        'Critical Care Medicine':   (-8, 0, 'right'),
        'Neurology':                (-8, 6, 'right'),
        'Nephrology':               (-8, -7, 'right'),
        'Rheumatology':             (8, 3, 'left'),
        'Infectious Disease':       (8, -3, 'left'),
        'Dermatology':              (8, 6, 'left'),
        'Hepatology':               (8, -5, 'left'),
        'Gastroenterology':         (8, 0, 'left'),
        'Psychiatry':               (8, 0, 'left'),
        'Orthopaedic Surgery':      (8, 0, 'left'),
        'Pediatrics':               (-8, 0, 'right'),
        'General Surgery':          (8, 0, 'left'),
        'Otolaryngology':           (8, 0, 'left'),
    }

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 6))

    for ax, ykey, ylabel, title, offsets, exclude_psych in [
        (ax1, 'pct_a', '% Supported by Level A Evidence',
         'A', PANEL_A, False),
        (ax2, 'pct_de', '% Supported by Level D-E Evidence',
         'B', PANEL_B, False),
    ]:
        plot_specs = [sp for sp in data if not (exclude_psych and sp == 'Psychiatry')]

        for sp in plot_specs:
            d = data[sp]
            # Jitter overlapping dots (Otolaryngology & General Surgery both n=30, 6.7% A)
            x_plot = d['n']
            y_plot = d[ykey]
            if ykey == 'pct_a' and sp == 'Otolaryngology':
                y_plot += 0.6
            elif ykey == 'pct_a' and sp == 'General Surgery':
                y_plot -= 0.6
            ax.scatter(x_plot, y_plot, s=80, color=DOT_COLOR, alpha=0.85,
                       edgecolor='white', lw=0.9, zorder=5)

        for sp in plot_specs:
            d = data[sp]
            label = SHORT_SPECS.get(sp, sp)
            dx, dy, ha = offsets.get(sp, (8, 0, 'left'))
            ax.annotate(label, (d['n'], d[ykey]),
                        xytext=(dx * 1.3, dy), textcoords='offset points',
                        fontsize=9.5, color='#333', ha=ha, va='center')

        ax.set_xscale('log')
        ax.set_xlim(90, 11000)
        ax.set_xlabel('Number of Recommendations (log scale)', fontsize=12)
        ax.set_ylabel(ylabel, fontsize=12)
        ax.tick_params(axis='both', labelsize=10.5)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.set_title(title, fontsize=13.5, fontweight='bold', loc='left', pad=10)

        if exclude_psych:
            ax.set_ylim(-2, 35)
        else:
            ymax = max(data[sp][ykey] for sp in plot_specs)
            ax.set_ylim(-3, ymax * 1.08)

    fig.tight_layout(w_pad=4)
    for fmt in ('pdf', 'png'):
        fig.savefig(FIG_DIR / f'figure3_dotplot.{fmt}', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('Figure 2 saved')


# ─────────────────────────────────────────────────
# eFigure 1 — Sensitivity ranking
# ─────────────────────────────────────────────────
def efigure1(primary_specs):
    specs = {s: [r['score'] for r in v] for s, v in primary_specs.items()}

    scenarios = OrderedDict([('Conservative\n(-0.25)', -0.25), ('Base', 0), ('Generous\n(+0.25)', 0.25)])
    rankings = {}
    for lab, delta in scenarios.items():
        gaps = {s: 1 - statistics.mean([max(0.125, min(1.0, n + delta)) for n in norms]) for s, norms in specs.items()}
        rankings[lab] = sorted(gaps, key=gaps.get, reverse=True)

    fig, ax = plt.subplots(figsize=(6, max(4, 0.25 * len(specs) + 1)))
    slabs = list(scenarios.keys())
    ns = len(specs)
    for sp in specs:
        pos = [rankings[sc].index(sp) for sc in slabs]
        mx = max(abs(p - pos[1]) for p in pos)
        col = '#1b4f72' if mx == 0 else '#85c1e9' if mx <= 1 else '#c0392b'
        ax.plot(range(3), pos, 'o-', color=col, alpha=0.8, ms=5, lw=1.5 if mx == 0 else 1.2)
        ax.text(2.15, pos[-1], SHORT_SPECS.get(sp, sp), fontsize=6, va='center', color=col,
                fontweight='bold' if mx == 0 else 'normal')

    ax.set_xticks(range(3))
    ax.set_xticklabels(slabs, fontsize=7.5)
    ax.set_ylabel('Rank (1 = largest gap)', fontsize=8)
    ax.set_ylim(ns - 0.5, -0.5)
    ax.set_yticks(range(ns))
    ax.set_yticklabels([str(i + 1) for i in range(ns)], fontsize=7)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.set_xlim(-0.2, 3.5)
    ps = [mpatches.Patch(color='#1b4f72', label='Stable'),
          mpatches.Patch(color='#85c1e9', label='Minor (1 pos)'),
          mpatches.Patch(color='#c0392b', label='Major (2+ pos)')]
    ax.legend(handles=ps, fontsize=6, frameon=True, facecolor='white', edgecolor='#ddd', loc='lower left')

    fig.tight_layout()
    for fmt in ('pdf', 'png'):
        fig.savefig(FIG_DIR / f'efigure2_sensitivity_ranking.{fmt}', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('eFigure 2 (sensitivity ranking) saved')


# ─────────────────────────────────────────────────
# eFigure 2 — Access coverage by society
# ─────────────────────────────────────────────────
def efigure2(soc_gl_count):
    cov = []
    for soc in sorted(soc_gl_count.keys()):
        ext = soc_gl_count[soc]
        if soc in FULLY_COMPLETE:
            tot = ext
        else:
            tot = max(AUDIT_DENOM.get(soc, ext), ext)
        cov.append((soc, tot, ext))

    cov.sort(key=lambda x: -x[1])

    fig, ax = plt.subplots(figsize=(6.5, max(5.5, 0.28 * len(cov) + 1)))
    for yi, (soc, tot, ext) in enumerate(cov):
        ax.barh(yi, ext, height=0.55, color='#2980b9', edgecolor='white', lw=0.3)
        ax.barh(yi, tot - ext, left=ext, height=0.55, color='#e5e5e5', edgecolor='white', lw=0.3)
        if ext > 0:
            ax.text(ext / 2, yi, str(ext), ha='center', va='center', fontsize=6, color='white', fontweight='bold')
        ax.text(tot + 0.8, yi, str(tot), ha='left', va='center', fontsize=6, color='#999')

    ax.set_yticks(range(len(cov)))
    ax.set_yticklabels([s for s, _, _ in cov], fontsize=7)
    ax.set_xlabel('Number of Guidelines', fontsize=8)
    ax.invert_yaxis()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    tot_all = sum(t for _, t, _ in cov)
    tot_ext = sum(e for _, _, e in cov)
    ps = [mpatches.Patch(color='#2980b9', label=f'Extracted ({tot_ext}, {tot_ext / tot_all * 100:.0f}%)'),
          mpatches.Patch(color='#e5e5e5', label=f'Not accessible ({tot_all - tot_ext})')]
    ax.legend(handles=ps, fontsize=7, frameon=True, facecolor='white', edgecolor='#ddd', loc='lower right')

    fig.tight_layout()
    for fmt in ('pdf', 'png'):
        fig.savefig(FIG_DIR / f'efigure2_access_coverage.{fmt}', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('eFigure 2 saved')


# ─────────────────────────────────────────────────
# eFigure 3 — Society-level distribution
# ─────────────────────────────────────────────────
def efigure3(recs_by_soc, soc_grading):
    by_soc = {s: v for s, v in recs_by_soc.items() if len(v) >= 20}
    order = sorted(by_soc, key=lambda s: statistics.mean([r['score'] for r in by_soc[s]]))

    n = len(order)
    fig_h = max(5.0, n * 0.38 + 1.5)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, fig_h),
                                    gridspec_kw={'width_ratios': [1.05, 1.0]})
    bh = 0.58

    # Panel A: Normalized
    for yi, soc in enumerate(order):
        total = len(by_soc[soc])
        tc = Counter(r['tier'] for r in by_soc[soc])
        left = 0
        for t in C:
            pct = tc.get(t, 0) / total * 100
            if pct > 0:
                ax1.barh(yi, pct, left=left, height=bh, color=C[t], edgecolor='white', lw=0.3)
                if pct >= 9:
                    ax1.text(left + pct / 2, yi, f'{pct:.0f}%', ha='center', va='center',
                             fontsize=5.5, color=_textc(C[t]), fontweight='bold')
                left += pct
        gap = 1 - statistics.mean([r['score'] for r in by_soc[soc]])
        ax1.text(103, yi, f'{gap:.2f}', ha='left', va='center', fontsize=6.5, fontweight='bold', color='#333')

    ax1.set_yticks(range(n))
    ax1.set_yticklabels([f'{s}  (n={len(by_soc[s])})' for s in order], fontsize=7)
    ax1.set_xlim(0, 100)
    ax1.invert_yaxis()
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    ax1.set_xlabel('% of Recommendations', fontsize=7.5)
    ax1.text(103, -0.6, 'Gap', ha='left', fontsize=6.5, fontweight='bold', color='#666')
    ax1.set_title('A. Normalized (A-E)', fontsize=8.5, fontweight='bold', loc='left', pad=8)
    patches = [mpatches.Patch(color=c, label=C_LABELS[t]) for t, c in C.items()]
    ax1.legend(handles=patches, loc='upper center', bbox_to_anchor=(0.5, -0.10),
               fontsize=5.5, frameon=False, ncol=3, columnspacing=1.0, handlelength=1.0)

    # Panel B: Original labels
    for yi, soc in enumerate(order):
        total = len(by_soc[soc])
        by_label = defaultdict(list)
        for r in by_soc[soc]:
            by_label[r['loe']].append(r['score'])
        sorted_labels = sorted(by_label, key=lambda l: -statistics.mean(by_label[l]))

        left = 0
        for lbl in sorted_labels:
            pct = len(by_label[lbl]) / total * 100
            tier = _tier(statistics.mean(by_label[lbl]))
            color = C[tier]
            ax2.barh(yi, pct, left=left, height=bh, color=color, edgecolor='white', lw=0.3)
            if pct >= 12:
                ax2.text(left + pct / 2, yi, lbl, ha='center', va='center',
                         fontsize=5.5, color=_textc(color), fontweight='bold')
            left += pct

        dom_gs = soc_grading[soc].most_common(1)[0][0] if soc_grading[soc] else ''
        short_gs = dom_gs.replace('GRADE_', '').replace('_', ' ').split('(')[0].split(' ')[0][:12]
        ax2.text(102, yi, short_gs, ha='left', va='center', fontsize=5.5, color='#999', style='italic')

    ax2.set_yticks(range(n))
    ax2.set_yticklabels(order, fontsize=7)
    ax2.set_xlim(0, 100)
    ax2.invert_yaxis()
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    ax2.set_xlabel('% of Recommendations', fontsize=7.5)
    ax2.text(102, -0.6, 'System', ha='left', fontsize=5.5, fontweight='bold', color='#666')
    ax2.set_title('B. Original Labels', fontsize=8.5, fontweight='bold', loc='left', pad=8)

    fig.suptitle('eFigure 3.  Evidence Level Distribution by Society',
                 fontsize=10, fontweight='bold', y=1.01)
    fig.tight_layout()
    for fmt in ('pdf', 'png'):
        fig.savefig(FIG_DIR / f'efigure3_society_distribution.{fmt}', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('eFigure 3 saved')


def main():
    print('Loading deduped data...')
    recs_by_spec, recs_by_soc, soc_gl_count, spec_gl_count, soc_grading = load_data()

    primary = primary_filter(recs_by_spec, spec_gl_count)
    total_recs = sum(len(v) for v in primary.values())
    print(f'  {total_recs} LoE recs across {len(primary)} primary specialties (>=5 GL)')
    print(f'  {sum(soc_gl_count.values())} guidelines from {len(soc_gl_count)} societies\n')

    print('Generating figures...\n')
    figure1(primary)
    figure2(primary)
    efigure1(primary)  # -> efigure2_sensitivity_ranking (eFigure 2; PRISMA is eFigure 1)
    # Retired from the supplement:
    #   efigure2 (access coverage) -> covered by eTable 2
    #   efigure3 (society distribution) -> raw per-society data in Supplementary Data File
    print(f'\nAll figures saved to {FIG_DIR}')


if __name__ == '__main__':
    main()
